spring:
  application:
   name: DbCheckingInMS

  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

server:
  port: 9020
