buildpacks:
  message : "Welcome to Microservice Playgraound BuildPack QA Sys API"
  contactDetails:
    name : "QA SHA P"
    email: "QASHA@gmail.com"
  onCallSupport:
    - (4444) 56756-433344
    - (555) 9999 - 454
