spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password:

  datasource:
    url: jdbc:h2:mem:testdb # In-memory database named 'testdb'
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

server:
  port: 9030

dbcheckinfo:
  message : "Welcome to Microservice Playgraound DbCheck-MS API"
  contactDetails:
    name : "Shajahan P"
    email: "shajahanvzm@gmail.com"
  onCallSupport:
    - (4444) 444404-444
    - (555) 5353 - 3434