jibinfo:
  message : "Welcome to Microservice Playgraound JIB GOOGLE PROD API"
  contactDetails:
    name : "ShaPROD P"
    email: "ShaPROD@gmail.com"
  onCallSupport:
    - (4444) 444404-444
    - (555) 5353 - 3434
